name: my_portfolio
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_theme_switcher: ^2.0.6
  google_fonts: ^5.1.0
  flutter_riverpod: ^1.0.3
  responsive_framework: ^0.1.7
  url_launcher: ^6.1.12



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/social/
    - assets/images/technology/
    - assets/images/

